//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEA_ErpProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKonsinyeGonderimler
    {
        public int Id { get; set; }
        public string CariTur { get; set; }
        public string CariAdi { get; set; }
        public int CariId { get; set; }
        public System.DateTime GonderimTarih { get; set; }
        public string Aciklama { get; set; }
        public int UrunId { get; set; }
        public int Adet { get; set; }
        public bool isDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedUser { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual tblStokDurum tblStokDurum { get; set; }
    }
}
