//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEA_ErpProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStokDurum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStokDurum()
        {
            this.tblKonsinyeGonderimler = new HashSet<tblKonsinyeGonderimler>();
        }
    
        public int Id { get; set; }
        public string Barkod { get; set; }
        public string UrunKodu { get; set; }
        public string LotSeriNo { get; set; }
        public Nullable<int> StokAdet { get; set; }
        public Nullable<int> RafAdet { get; set; }
        public Nullable<int> KonsinyeAdet { get; set; }
        public Nullable<int> SubeAdet { get; set; }
        public Nullable<int> UrunHareketAdet { get; set; }
        public string SutKodu { get; set; }
        public string BransNo { get; set; }
        public Nullable<bool> UTS { get; set; }
        public Nullable<System.DateTime> UretimTarih { get; set; }
        public Nullable<System.DateTime> SonKullanmaTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKonsinyeGonderimler> tblKonsinyeGonderimler { get; set; }
    }
}
