//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEA_ErpProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrunGirisAlt
    {
        public int Id { get; set; }
        public Nullable<int> GirisId { get; set; }
        public string Barkod { get; set; }
        public string UrunKodu { get; set; }
        public string LotSeriNo { get; set; }
        public Nullable<int> GirisAdet { get; set; }
        public Nullable<System.DateTime> GirisTarih { get; set; }
        public string BransNo { get; set; }
        public Nullable<bool> UTS { get; set; }
        public Nullable<System.DateTime> UretimTarihi { get; set; }
        public Nullable<System.DateTime> SonKullanmaTarihi { get; set; }
        public string Aciklama { get; set; }
    }
}
